### ISSUE TITLE
Hib Hometown

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1100]
Below you'll find the roomnumbers and info to setup hometown for Hib.  Let me know if you need anything else.  

HIB MAPPING

```
Hib:
  currency: dokora
  leather_repair:
    id: 11211
    name: Ladar
  metal_repair:
    id: 11211
    name: Ladar
  deposit:
    id: 11214
  exchange:
    id: 11213
  gemshop:
    id: 8899
    name: rasiya
  tannery:
    id: 8885
    name: Vandorf
  npc_empath:
    id: 8881
  locksmithing:
    id: 
  theurgy_supplies:
    id: 
```
