### ISSUE TITLE
REQUEST - Combat PRE-BUFF Room

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1203]
Request to be able to choose a room by room number where a toon can pre-buff before initiating a combat or hunting yaml.

Maybe allow it to work in hunting_file_list: so it can be manually adjusted

**Comment by jayRyan24** [comment]
I too had separate YAMLs doing this for me. Initial support added.

Pull Request = #1211

**Comment by Aurayn** [comment]
That is great jay!  What are your thoughts on how it will work?

**Comment by rcuhljr** [comment]
https://github.com/rpherbig/dr-scripts/issues/790

**Comment by jayRyan24** [comment]
It uses existing data structures and systems we have in place. You set up a waggle_set for it, it will call it before it "hunts", you can also set a room number for it to goto to do said buffing. This isn't as thorough as it will be, but it's good as a start.

**Comment by Aurayn** [comment]
Could I trouble you for an example so I can try it out?

**Comment by rpherbig** [comment]
```
prehunt_buffs: 1375

waggle_sets:
  prehunt_buffs:
    Sure Footing:
      abbrev: SUF
      recast: 2
      mana: 15
      cambrinth:
      - 25
      - 25
```
