### ISSUE TITLE
steal script - different YAML formatting?

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1399]
I don't know a whole heck of a lot about YAML formatting but this one seems difficult to parse through and organize. Has anyone considered a different structure?

New
```
zoluren:
  crossing:
    room: 19076
    name: alchemist shop
    items:
      - water: in vat
        pawnable: false
        id: 0
        min:
         trivial: 0
         nearly: 4
         acceptable: 2
         vpoorly: 3
         poorly: 3
         rather: 3
        max:
         trivial: 0
         nearly: 4
         acceptable: 2
         vpoorly: 3
         poorly: 3
         rather: 3
      - candle mold: on table
        pawnable: false
        id: 0
        min:
         trivial: 0
         nearly: 4
         acceptable: 2
         vpoorly: 3
         poorly: 3
         rather: 3
        max:
         trivial: 0
         nearly: 4
         acceptable: 2
         vpoorly: 3
         poorly: 3
         rather: 3

```   

Old
```
- province: zoluren
  item: water
  item_in: in vat
  room: 19076
  pawnable: false
  id: '0'
  trivial_max: 1750
  acceptable_max: 2
  acceptable_min: 0
  nearly_max: 41
  nearly_min: 4
  poorly_max: 3
  poorly_min: 3
  trivial_min: 42
- province: zoluren
  item: candle mold
  item_in: on table
  room: 19076
  pawnable: false
  id: '1'
  acceptable_min: 83
  acceptable_max: 149
  trivial_max: 1750
  trivial_min: 218
  poorly_max: 150
  poorly_min: 150
  rather_max: 82
  rather_min: 82
  vpoorly_max: 217
  vpoorly_min: 210
```
