### ISSUE TITLE
Add Stop Events to hunting buddy

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1649]
Hunting buddy currently ends hunting based on experience and time (via `stop_on` and `duration`). It would be useful for users to end hunting on 'events' where an event is something like "my box container is full" or "im healed (and a necromancer or empath)". Events are quantifiable like, `DRCH.check_health.empty?`, `box_container_full?`, existing or new functionality respectively. Hunting buddy would end the hunt the same way it ends hunts via time or experience.

**Comment by jandersson** [comment]
settings might look something like this:
```
 hunting_info:                
 - :zone: shard_kobolds                         
   stop_events:               
     - healed
     - boxes: full
     - skins: 20   
```
Where we want to stop hunting kobolds when healed, box container is full, skin count is >= 20
