### ISSUE TITLE
Combat prep section

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#167]
I'd like to stop in a room outside the hunting area and put up a few pre-buffs. Cyclic debuffs, shield of light, etc.

**Comment by rpherbig** [comment]
This would be great for summoned weapons too.

**Comment by rcuhljr** [comment]
combat prep and clean up, add optional waypoints towards and away from hunting spot

```
hunting_info:
- :zone: black_goblins
  entry:
  - 851
  - 4366
  - 3457
  prebuff:
    room: 4366
    actions:
    - Instinct
    - Hands of Lirisia
  exit:
  - 3457
  - 851
  args:
  - d0
  stop_on:
  - Light Armor
  - Small Edged
  - Shield Usage
  - Parry Ability
  - Bow
  - Evasion
  - Stealth

```
