### ISSUE TITLE
Zombie Creation and Usage

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1824]
It would be nice to have support for making a zombie and summoning during combat. A potential settings dictionary could look like: 
```yaml
zombie:
  make: true  # Creates a zombie if there are none to summon
  summon: true  # Summons a zombie at start of combat, dismisses at the end.
  stance: balanced
  behavior: defensive
  use_rpu: true # Use RPU spell to buff zombie
  use_nr: true  # Use NR to heal zombie
  tm_focus: tetractys  #  Use a TM focus during creation

waggle_sets:
  zombie:
     CFB data 
     NR data   
     RPU data
```
