### ISSUE TITLE
pick - Lockpick buffs for thieves

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#241]
khri focus + khri sight + khri safe = khri secure

https://elanthipedia.play.net/mediawiki/index.php/Category:Khri

**Comment by rpherbig** [comment]
@OdnaZvezda Does the `lockpick_buffs` setting work for this? My assumption is no since that assumes a spell and I believe Khri are not prepped?

**Comment by OdnaZvezda** [comment]
Correct

**Comment by rcuhljr** [comment]
```yaml
lockpick_buffs:
  khri:
    - focus
    - safe
    - sight
```
