### ISSUE TITLE
Facilitate easily switching combat args without moving rooms

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#254]
So I want to run two sets of args in the same hunting area, I'd like to not have to fire the exit script to leave the area and the find room script to look around for another hunting room without mobs when I still have mobs left in my current room.

```
- :zone: bristle_peccs
  args:
  - d2
  - app
  stop_on:
  - Chain Armor
  - Light Armor
  - Small Edged
  - Shield Usage
  - Parry Ability
  - Debilitation
- :zone: bristle_peccs
  args:
  - d0
  - app
  stop_on:
  - Bow
```

would become

```
- :zone: bristle_peccs
  trains:
   - args:
    - d2
    - app
    stop_on:
    - Chain Armor
    - Light Armor
    - Small Edged
    - Shield Usage
    - Parry Ability
    - Debilitation
 -  args:
    - d0
    - app
    stop_on:
    - Bow
```
