### ISSUE TITLE
training manager skill switching bug

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#318]
if the skill set for `training_manager_priority_skills` is not the skill in the first set of `hunting_info`, but the `stop_on` skill is already locked, `hunting-buddy` tries to cycle to the next set, but fails and doesn't handle the error. 

```
training_manager_hunting_priority: true
training_manager_priority_skills:
- Light Thrown
hunting_info:
- :zone: rock_trolls
  args:
  - sling
  stop_on:
  - Slings
- :zone: thicket_vipers
  args:
  - back
  stop_on:
  - Light Thrown
  - Heavy Thrown
  :duration: 10
- :zone: geni
  args:
  :duration: 10
  stop_on:
  - Stealth
```

in this case, my slings was 34/34 but light thrown was 2/34, this is what happens:

```
--- Lich: go2 has exited.
[hunting-buddy: stopping due to skills]
--- Lich: combat-trainer active.
>
[combat-trainer]>stance set 100 40 40
Setting your Evasion stance to 100%, your Parry stance to 40%, and your Shield stance to 40%.  You have 4 stance points left.
>
```
