### ISSUE TITLE
Settings nagger and transform.

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#3583]
Someone should implement a settings nagger+transformer to allow us to rename yaml settings.

`data-transitions.lic`
```yaml
transitions:
  oldkey:
    new_name: newkey
    change_date: timestamp in the future that support stops
```

`;update-settings` -> Go through yaml files (all? character?) as raw text files replacing oldkey occurences with newkey. Maybe this is just a setting on validate?

Have dependency nag once every few minutes if any outdated settings are present, let them know how long until their yaml breaks and the options for fixing the problem. Let them type CONFIRM IGNORE or do something like `;e stop_nag` to make it go away for the session. Actually change settings on the date promised, receive bacon.
