### ISSUE TITLE
combat-trainer hangs on when spell casting fails due to low skill

### ISSUE THREAD

**Issue by kara-ryli** [rpherbig/dr-scripts#3883]
When a spellcast fails due to low skill (but not due to mana or backfire), combat-trainer hangs and stops sending commands. See attached log stops responding for an entire minute. Repeatable 100% (or as often as you can get your casts to fail).

I tried to look into this, but as far as I could tell, `DRCA.cast?` treats these failures all the same, so why this particular failure hangs combat-trainer I couldn't immediately figure out.

[combat-trainer-hang.txt](https://github.com/rpherbig/dr-scripts/files/3624431/combat-trainer-hang.txt)

Relevant YAML:

```yaml
buff_spells:
  Guardian Spirit:
    abbrev: gs
    mana: 5
    recast: 0
    cyclic: true
    cast: cast
    command: warrior to behavior aggressive
    expire: appears suddenly less real
```
