### ISSUE TITLE
trade.lic

### ISSUE THREAD

**Issue by FuginSteve** [rpherbig/dr-scripts#4294]
Trade.lic was giving this error -very possibly a problem on my end since I just started using LICH

EndUpdate
Specified argument was out of the range of valid values.
Parameter name: position

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: position
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at ns6.FormMain.method_112(String& sText, Color& oColor, Color& oBgColor, FormSkin& oTargetWindow, Boolean bNoCache, Boolean bMono, Boolean bPrompt, Boolean bInput)
   at ns6.FormMain.method_113(String& sText, Color& oColor, Color& oBgColor, Enum0& oTargetWindow, String& sTargetWindow, Boolean bNoCache, Boolean bMono, Boolean bPrompt, Boolean bInput)
   at ns6.FormMain.method_127()

**Comment by FuginSteve** [comment]
here is a pastebin of the .lic when this error comes up

https://pastebin.com/Tew23nZ0

**Comment by Tarhish** [comment]
Lich is definitely confused because it's trying to run some other genie script.  I'm not a genie person myself, but I think it's trying to buff you and it is fighting with Lich?  Perhaps something is on a trigger and activating when you start up trade.

Since you say you're new to the install, did you try https://github.com/rcuhljr/dr-lich and set the genie option during startup?

**Comment by FuginSteve** [comment]
Thank you for the response. The end all issue was I had a genie script
called buff, so every time Trade tried to access buff.lic it was getting
confused. I have removed the script and no more issues. The only issue I
have now is that the script doesnt train magic or crafting while traveling.

**Comment by Tarhish** [comment]
Good to hear you solved it.  As for training, feel free to ask questions, though the basics of setting it up for training is out at https://github.com/rpherbig/dr-scripts/wiki/Trader-Tutorials in the caravan section.

Generally speaking, though, if you are set up for training crafting in crossing-training it'll work here if you call out the skill in caravan_training_skills: and magic training needs to be called out in caravan_training_skills with a crafting_training_spells: section like

```
crafting_training_spells:
  Utility:
    abbrev: NOU
    symbiosis: true
    mana: 20
  Augmentation:
    abbrev: MEG
    symbiosis: true
    mana: 25
  Warding:
    abbrev: NON
    symbiosis: true
    mana: 25
```

**Comment by FuginSteve** [comment]
So i have tried that and it still never swung through the crafting
societies when it hit Crossing.

Here is my current Yaml - originally I followed the link you posted pretty
closely I just still haven't be able to get it to work.

https://pastebin.com/jaDCF23N

I've stepped away from it for now as it was getting super frustrating
trying to figure it out.

**Comment by Tarhish** [comment]
One thing you'll want -- the setting is caravan_training_skills, and you've got caravan_trading_skills instead, which is why it's not doing what you want it to. 

Since the script doesn't see an entry, it's using the default in base.yaml, which is:

```
caravan_training_skills:
  # Augmentation: 5
  # Warding: 5
  # Utility: 5
  Performance: 120
  Appraisal: 60
  Attunement: 100
  Outdoorsmanship: 5
  Locksmithing: 30
  Perception: 45
  First Aid: 120
```

So it won't try to cast magic or craft at all.  I'd try changing the spelling first off and see how it behaves.  It'll try to make earcuffs and double-wrapped belts instead of the script-defined shaping and knitting, because you've got a caravan_recipes: override set, which is probably fine, but keep it in mind if it's not making something helpful for you.

The other thing is, those times in caravan_training_skills might pose a problem.  I assume they're that low cause you were trying things out and trying to get it to work, but it means that when it's done outfitting or engineering it'll wait a whole 5 seconds before looking to see if it wants to train it again.  Be careful, because if the recipe you've chosen above isn't training well it could monopolize your time.
