### ISSUE TITLE
Request for feature - Refactor of Herbs in combat.

### ISSUE THREAD

**Issue by jbrock24** [rpherbig/dr-scripts#4296]
The below code needs to be refactored out of training_abilities. I am not even sure how this got through to master, but the fact is that `training_abilities` are skills that train based on a set timer check. This is a kludge addition to just get it through, and it feels this was simply out of not knowing how the system works properly so they didn't know where to add this. 

My suggestion is a `check_healing` placement or a `check_herbs` placement. This can be achieved 3 ways.
1.) An argument is passed, this will require a timer based on an internal clock we set up, say 600 seconds. 
```
hunting_info: 
- :zone: 
  - young_cave_trolls
  args:
  - d0
  - herbs
  :duration: 60
  stop_on:
  - Bow
```

2.) A boxes style. This lets us add a customized timer.
```
- :zone:
  - cabalist
  - archons
  args:
  - d0
  - boxes
  boxes: true
  herbs: 600
  :duration: 30
```
3. A new setting, `use_herbs_hunting: 600`

I think the best way is number 1, it basically lets us reduce yet another setting to add to setup, I think most people use 600 standard, so it should be fine.

Note: This will need backward compatibility for a while, adding in a check to training_abilities, if found there, remove it from the list and flag this setting as true with a warning out to the user that this setting is deprecated. Also needs a validate warning.
