### ISSUE TITLE
Workorders

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#4308]
So I've tried leaving the difficulties for workorders off.  I've been told to get techniques so I got those.  Then I've tried to use the difficulties but each time it has my character ask back to back to back about getting <difficulty> workorder for almost 10 minutes before giving up and doing the next thing in my yaml.

Any suggestions or could we possibly get a fix for that?
https://pastebin.com/ajgBireC

```
craft_max_mindstate: 31
workorder_min_items: 2
workorder_max_items: 5
train_workorders:
# - Blacksmithing
# - Shaping
# - Tailoring
 - Remedies
workorder_diff:
  remedies: challenging
crafting_container: leather satchel
alchemy_belt:
  name: grass toolstrap
  items:
  - iron mortar
  - iron pestle
  - mixing stick
  - wire sieve
```
