### ISSUE TITLE
Crossing-training

### ISSUE THREAD

**Issue by Jandrel1** [rpherbig/dr-scripts#4327]
Crossing-training has worked great for me but all the sudden all it will do is run the the Ranger's Guild and try and play scales with Zills.  I don't currently have zills so this is hanging me up.  Is there a way to switch this off so that I can just run the script normally for the other skills?

**Comment by jandersson** [comment]
I think something is wrong with your config file/profile. 

Can you paste a pastebin of your profile here? 
1. While on your character having the issue, do `;e help_me('Yourcharactername')`. Replace `Yourcharactername` with your character name
2. You'll private message yourself on lnet with a link to pastebin containing all the config files for your character along with some additional info.
3. Paste that link here or if steps 1 or 2 didn't work mention it here (preferably with an error message)

**Comment by Jandrel1** [comment]
Thanks, this is what I'm getting as a response:
>;e help_me Kaldred
--- Lich: exec1 active.
--- Exception: uninitialized constant Kaldred
exec1:1:in `_script'
--- Lich: exec1 has exited.

**Comment by jandersson** [comment]
> ;e help_me Kaldred

Put quotes around your name `;e help_me "Kaldred"`

**Comment by Jandrel1** [comment]
;e help_me "Kaldred"
--- Lich: exec1 active.
--- Lich: exec1 has exited.

**Comment by Jandrel1** [comment]
oops missed it over in thoughts.....
https://pastebin.com/DD8LTAWv

**Comment by jandersson** [comment]
I found one issue with Clear vision and Artificers eye being indented differently than the other spells... here is the correction:
```yaml 
---
# https://elanthipedia.play.net/Moon_mage#Circle_Requirements
# 4 Magics: Augmentation, Attunement, Arcana, Targeted Magic/Debilitation (Does not include Lunar Magic or Astrology)
# 4 Survivals: Perception, Athletics, Evasion, Skinning (Does not include Thievery)
# 3 Lores: Appraisal, Tactics, Mechanical Lore (Does not include Scholarship)
# 2 Additional: Astrology, Scholarship
 
# It is recommended to get a target or debilitation spell for your second circle. (e.g. Dinazen Olkar or Calm)
# Please see the 'offensive_spells:' setting below for a commented (unused) example. Uncomment to begin usage (remove #'s).
 
# Eventually you will need to train 3 more Magics to circle (for a total of 7)
# Eventually you will need to train 1 more Survival to circle (for a total of 5)
 
# Hunting settings
training_manager_hunting_priority: true
training_manager_priority_skills:
- Heavy Thrown
- Shield Usage
hunting_info:
- :zone: dire_bears
  stop_on:
  - Heavy Thrown
  - Shield Usage
  - Evasion
  - Skinning
  - Tactics
 
# Gear settings
gear:
# - :adjective: example
#   :name: gear
#   :is_leather: true
#   :hinders_lockpicking: false
#   :is_worn: true
- :adjective: rugged
  :name: gloves
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: rugged
  :name: leathers
  :is_leather: true
  :hinders_lockpicking: false
  :is_worn: true
- :adjective: rugged
  :name: cowl
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: target
  :name: shield
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: parry
  :name: stick
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :adjective: brass
  :name: knuckles
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: elbow
  :name: spikes
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :adjective: steel hurlable war
  :name: hammer
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: false
gear_sets:
  standard:
  - rugged leathers
  - rugged cowl
  - rugged gloves
  - target shield
  - parry stick
  - brass knuckles
  - elbow spikes
 
# Combat settings
 
# Uncomment (remove #'s) to train Targeted Magic/Debilitation with the listed spells (or change to use different spells).
offensive_spells:
  - skill: Targeted Magic
    name: Dinazen Olkar
    abbrev: do
    cast_only_to_train: true
    mana: 10
  - skill: Debilitation
    name: Calm
    abbrev: calm
    mana: 10
    harmless: true
 
buff_spells:
  Shadows:
    abbrev: shadows
    recast: 1
    mana: 10
    cambrinth:
    - 1
 
dance_skill: Large Blunt
training_abilities:
  Stealth: 60
  Tactics: 20
  PercMana: 240
  Hunt: 80
 
weapon_training:
  Brawling: ''
  Heavy Thrown: steel hurlable war hammer
  Large Blunt: steel hurlable war hammer
priority_weapons:
  - Brawling
  - Heavy Thrown
use_stealth_attacks: true
 
skinning:
  skin: true
  arrange_all: false
  arrange_count: 0
  tie_bundle: true
 
# Non-combat settings
exp_timers:
  Astrology: 200
  Attunement: 130
 
crossing_training:
- Astrology
- Augmentation
- Scholarship
- Attunement
- Appraisal
- Athletics
- Perception
- Mechanical Lore
have_telescope: false
 
safe_room: 6871
 
training_spells:
  Augmentation:
    abbrev: shadows
cambrinth: cambrinth ring
cambrinth_cap: 5
favor_god: Meraud
favor_goal: 10
 
waggle_sets:
  astrology:
    Clear Vision:
      mana: 20
    Artificer's Eye:
      mana: 20
      cambrinth:
      - 10
    Aura Sight:
      mana: 20
      cambrinth:
      - 10
    Psychic Shield:
      mana: 20
      cambrinth:
      - 10
    Refractive Field:
      mana: 20
      cambrinth:
      - 10
 
 
   
 
 
 
astrology_training:
- observe
# - rtr
- events
- weather
- attunement
# - ways
appraisal_training:
- art
```
Can you try this and see if it works?
