### ISSUE TITLE
Missing documentation for arrange_types setting - add to base.yaml

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#4681]
I just found out that there is a feature that allows users to choose whether to use 'skin' or 'part' when arranging specific creature types. It's not an issue that comes up a lot, but it has a couple of legitimate use cases.

I suggest adding some comments to base.yaml in the section that deals with skinning:

```
# To use arrange_all, make sure to set arrange_count to 1
# To specify whether to "arrange for skin" or "arrange for part", list the creature name under arrange_types followed by part or skin
skinning:
  skin: true
  arrange_all: false
  arrange_count: 0
  tie_bundle: false
#  arrange_types:    
#    wyvern: part (example, list the noun of the creature name followed by 'skin' or 'part')
```

This avoids cases where the default "arrange for skin" always fails, leading to wasted commands. It also helps hunters who are gathering specific materials for outfitting or engineering projects.

edit: Ignore the quotes before the comments, I'm not great at the formatting.
edit: @rpherbig here - I updated the formatting for clarity
edit: thanks for that, and I also wanted to add "bone" to the list of arrange options which would be useful for harvesting engineering materials (assuming that this option works).
