### ISSUE TITLE
Combat-trainer no longer buffs Ethereal Fissure

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#472]
Excerpt from Torgro's yaml:
```
buff_spells:
  Ethereal Fissure:
    abbrev: ETF
    recast: -1
    mana: 15
    cambrinth:
    - 15
    - 15
    - 15
    expire: fissure collapses in on itself, winking out of existence
    cast: cast fire
```

This used to work but no longer does.
