### ISSUE TITLE
workorder script not properly handling blue flowers (through remedies)

### ISSUE THREAD

**Issue by Nituki** [rpherbig/dr-scripts#4728]
When trying to craft refreshment elixirs, the workorder script fails to process the blue flowers (see below):
[workorders: blue flowers]

--- Lich: alchemy active.

--- Lich: error: comparison of Integer with nil failed
    alchemy:58:in `<'
    alchemy:58:in `forage_ingredient'

and then when alchemy runs it doesn't know what ingredient to use first and leaves it blank:

[alchemy]>count my first  in my ritual pack

**Comment by Dartellum** [comment]
The code has not changed in years for red|blue flowers and the handling of them. However, other weirdness has happened. I will take a look and see if I can resolve this soon. No promises on time, I have several other updates and enhancements in the works.

**Comment by Dartellum** [comment]
Also, 
```yaml
- name: some refreshment elixir
  noun: elixir
  volume: 1
  type: remedies
  work_order: false
  chapter: 2
  container: bowl
  herb1: blue flowers
  herb1_stock:
  herb2: belradi
  herb2_stock:
  catalyst: coal nugget
  catalyst_stock: 2
  catalyst_volume: 10
```
Not sure how you are doing workorders of this recipe unless you changed it to true in your base-recipe file. 

I can put some time into trying to fix it but I could not a long time ago and made the recipe **false**.
