### ISSUE TITLE
Add spell stances to buff scripts and yaml entries

### ISSUE THREAD

**Issue by robbintt** [rpherbig/dr-scripts#5075]
Spell stance can make a big difference but varies based on the spell. This is a good opportunity for the buff yaml options.

**Comment by KatoakDR** [comment]
I could see a few ways this could be implemented based on what I've read on the [wikk](https://elanthipedia.play.net/Spells_command):

Specify the stance name and use whatever you've configured that to be:
```yaml
    Ethereal Shield:
      stance: potency
```

Specify the stance numeric values for granular control:
```yaml
    Ethereal Shield:
      stance: 80 120 100
```

We'd also need to introduce a `default_spell_stance` similar to `default_stance` for evasion/shield/parry.

**Comment by wstampley** [comment]
I'm not against this, but you can easily do it with before and afters on spells today.

**Comment by KatoakDR** [comment]
> I'm not against this, but you can easily do it with before and afters on spells today.
> 
> ```
>     Hydra Hex:
>       cyclic: true
>       cast: cast male offense
>       mana: #
>       recast: -1
>       before:
>       - message: spell stance X Y Z
>       after:
>       - message: spell stance X Y Z
> ```

I forgot about the before/after, neat! I think you also have to provide some match strings, too, to avoid a timeout on bput? Looks like the 'before/after' are done as `DRC.bput(action['message'], action['matches'])`

**Comment by KatoakDR** [comment]
I think the before/after could be a workaround for now. If there's more demand for customizing spell stances per spell I'm a fan of making it easier for folks to configure so a single `stance:` property on the spell helps.

**Comment by wstampley** [comment]
> > I'm not against this, but you can easily do it with before and afters on spells today.
> > ```
> >     Hydra Hex:
> >       cyclic: true
> >       cast: cast male offense
> >       mana: #
> >       recast: -1
> >       before:
> >       - message: spell stance X Y Z
> >       after:
> >       - message: spell stance X Y Z
> > ```
> 
> I forgot about the before/after, neat! I think you also have to provide some match strings, too, to avoid a timeout on bput? Looks like the 'before/after' are done as `DRC.bput(action['message'], action['matches'])`

I don't have any matches on mine and they seem to work? Don't know.

```
  om: &om
    Osrel Meraud:
      mana: X
      cambrinth: [X, X, X, X]
      recast: -1
      cast: cast my orb
      before:
      - message: spell stance 130 70 100
      after:
      - message: spell stance 115 115 70
      - message: release sap
      - message: tap orb
```
