### ISSUE TITLE
Please add Pasabas to base-recipes.yaml.

### ISSUE THREAD

**Issue by SekmehtDR** [rpherbig/dr-scripts#5205]
Please add Pasabas to base-recipes.yaml.

```
- name: a metal pasabas
  noun: pasabas
  volume: 5
  type: weaponsmithing
  work_order: true
  chapter: 1
  part:
  - hilt
```
