### ISSUE TITLE
Update to Base-Recipes.yaml

### ISSUE THREAD

**Issue by SekmehtDR** [rpherbig/dr-scripts#5214]
Please update block on line 3305.

```
- name: a metal hhr'ata
  noun: mallet
  volume: 10
  type: weaponsmithing
  work_order: true
  chapter: 5
  part:
  - haft
```
to:
```
- name: a metal hhr'ata
  noun: hhr'ata
  volume: 10
  type: weaponsmithing
  work_order: true
  chapter: 5
  part:
  - haft
```

Note that the noun does not match the weapon, in this case the noun should be hhr'ata
