### ISSUE TITLE
Update for base-recipes.yaml. Throwing Club Part Missing.

### ISSUE THREAD

**Issue by SekmehtDR** [rpherbig/dr-scripts#5221]
Line 3080 currently reads:

```
- name: a metal throwing club
  noun: club
  volume: 5
  type: weaponsmithing
  work_order: true
  chapter: 4
```

Please update to include the part noun "haft".

```
- name: a metal throwing club
  noun: club
  volume: 5
  type: weaponsmithing
  work_order: true
  chapter: 4
  part:
  - haft
```
