### ISSUE TITLE
Add support for necromancer healing in combat-trainer

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#546]
During the skinning and looting process, it would be good to have combat-trainer cast consume flesh to heal any wounds detected in 'health'. The user could specify a flag in their YAML file under the existing thanatology heading:

```
thanatology:
  necro: true
  ritual_type: dissect
  heal: true
```

I have a circle 28 necro, so I can take a swing at the issue
