### ISSUE TITLE
SLS night: true -- not working

### ISSUE THREAD

**Issue by Angel-DR** [rpherbig/dr-scripts#6352]
I was hoping we might be able to fix the night check on SLS.  It has never worked for me.  

I even tried adding day: false - neither work and it casts at night.  Can this be fixed? 

Thanking you in advance. 

    Starlight Sphere:
      mana: 27
      cast: cast spider
      night: true
      day: false
      cyclic: true

**Comment by vtcifer** [comment]
Can you run with combat-trainer in debug mode until it tries to cast SLS and paste the log here or in the discord?  Note:  combat-trainer in debug mode produces a LOT of extra text.  You may need to ensure your Front End is logging, as it may scroll off the window buffer.

You can enable debug mode for combat trainer by doing one the following:

1. Setting the UserVar combat_trainer_debug to true (`;vars set combat_trainer_debug=true`).  To turn it off after you are done, do `;vars delete combat_trainer_debug` or `;vars set combat_trainer_debug=false`)
2. If you use hunting-buddy to launch combat-trainer, adding the following arg to your yaml:
```yaml
hunting_info:
  - :zone: foobar
    :duration: 60
    stop_on:
    - Foo
    - Bar
    args:       # <---- this would be new if you don't use args currently in your hunting buddy config
      - d3
      - debug   # <---- this would be new, if you use args currently
```
3. If you run combat-trainer manually, by running it with the debug arg  on the command line, in addition to your normal settings: e.g. `;combat-trainer d2` -> `;combat-trainer d2 debug`

**Comment by Angel-DR** [comment]
Sure, I can do that for you and thank you!

Email back to you when done?

It's late evening now, so I'll wait for daytime. :)

**Comment by MahtraDR** [comment]
```
>;eq echo UserVars.sun['night']
[exec1: true]
```
```yaml
  sls: &sls
    Starlight Sphere:
      abbrev: sls
      mana: 30
      cast: cast spider
      night: true
```

![image](https://user-images.githubusercontent.com/93822896/215190149-a32041df-09bd-4d33-a749-15b27189dbd6.png)

What's the problem you're seeing?
