### ISSUE TITLE
base-town.yaml

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#638]
As a new script idea: what do you all think about having a base file for town room ID's? This would help do away with hard coded room ID's in several scripts and open up an avenue for expanding crossing-trainer to other towns. The user could define their 'home town' in their settings and that would be used by sell-loot and some other errand running scripts. Would this be too limited to be practical/worth the effort? I realize there are some things which are very much town specific and difficult to generalize (appraisal, athletics training and auto-healers spring to mind).
A suggested example:
```
Crossing:
  leather-repair: 12345
  metal-repair: 1234
  bank: 1900
  autopuff: dokt
Leth Deriel:
  bank: 123
  tannery: 12
  gemshop: you get the idea
  autopuff: elys
```
