### ISSUE TITLE
Smart study first aid compendiums based on skill.

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#822]

**Comment by rpherbig** [comment]
Is there a reliable way to tell them apart?

**Comment by rcuhljr** [comment]
We know the name of every chart and they have known scholarship requirements, we just need to enter the data.

**Comment by drboldwin** [comment]
is the idea here to carry multiple compendiums then?  or to just fill it with a wider skill range of charts and this would flip to the appropriate ones and study them?

**Comment by rcuhljr** [comment]
mostly the second, but really so I can give a compendium to a young character and it will study the appropriate ones as needed. How does this look?

`first_aid_charts:
- name: black goblin
  scholarship: ###
- name: rat
  scholarship: ###`

**Comment by rpherbig** [comment]
I assume `scholarship` is the min to try reading. Would it be worth having a `max_first_aid` that is when you should stop bothering?

**Comment by rcuhljr** [comment]
maybe? but I'm not terribly bothered and we'd have to gather all the data. It's a 10 second read that still gives some tiny exp I think.

**Comment by rpherbig** [comment]
10 seconds times the number of pages that aren't useful. And `crossing-training` will keep trying if it doesn't move your FA.

**Comment by rcuhljr** [comment]
It's never a problem I've had I guess.

**Comment by rpherbig** [comment]
I've stopped training FA on some of my guys because of it

**Comment by rcuhljr** [comment]
Well then you can start adding max: fields :P

**Comment by drboldwin** [comment]
```
first_aid_charts:
- name: Rat
  scholarship: 10
- name: Croff Pothanit
  scholarship: 20
- name: Heggarangi Frog
  scholarship: 20
- name: Brocket Deer
  scholarship: 30
- name: Scavenger Goblin
  scholarship: 30
- name: Wild Boar
  scholarship: 40
- name: Silver Leucro
  scholarship: 40
- name: Grass Eel
  scholarship: 50
- name: Striped Badger
  scholarship: 50
- name: Blood Dryad
  scholarship: 60
- name: Equine
  scholarship: 60
- name: Blood Nyad
  scholarship: 70
- name: Glutinous Lipopod
  scholarship: 70
- name: Kelpie
  scholarship: 80
- name: Trollkin
  scholarship: 80
- name: Boggle
  scholarship: 90
- name: Cougar
  scholarship: 90
- name: Dwarven
  scholarship: 100
- name: Elothean
  scholarship: 100
- name: Elven
  scholarship: 100
- name: Gnome
  scholarship: 100
- name: Gor'Tog
  scholarship: 100
- name: Halfling
  scholarship: 100
- name: Human
  scholarship: 100
- name: Kaldar
  scholarship: 100
- name: Prydaen
  scholarship: 100
- name: Rakash
  scholarship: 100
- name: S'Kra Mur
  scholarship: 100
- name: Boobrie
  scholarship: 120
- name: Snow Goblin
  scholarship: 120
- name: Thunder Ram
  scholarship: 120
- name: Copperhead Viper
  scholarship: 140
- name: Malodorous Bucca
  scholarship: 140
- name: Dusk Ogre
  scholarship: 160
- name: Young Ogre
  scholarship: 160
- name: Bison
  scholarship: 180
- name: Rock Troll
  scholarship: 180
- name: Sun Vulture
  scholarship: 180
- name: Fire Maiden
  scholarship: 200
- name: Moss Mey
  scholarship: 200
- name: Prereni
  scholarship: 220
- name: Vela'tohr Bloodvine
  scholarship: 220
- name: Peccary
  scholarship: 230
- name: Blue-belly Crocodile
  scholarship: 240
- name: Kashika Serpent
  scholarship: 240
- name: River Caiman
  scholarship: 260
- name: Sluagh
  scholarship: 260
- name: Wood Troll
  scholarship: 260
- name: Gidii
  scholarship: 280
- name: Black Goblin
  scholarship: 300
- name: Granite Gargoyle
  scholarship: 320
- name: Rhoat Moda
  scholarship: 320
- name: River Sprite
  scholarship: 320
- name: Bawdy Swain
  scholarship: 340
- name: Swamp Troll
  scholarship: 340
- name: Heggarangi Boar
  scholarship: 360
- name: Warcat
  scholarship: 360
- name: Blacktip Shark
  scholarship: 380
- name: Piranha
  scholarship: 380
- name: Lanky Grey Lach
  scholarship: 400
- name: Ape
  scholarship: 410
- name: Merrows
  scholarship: 420
- name: Selkie
  scholarship: 430
- name: Geni
  scholarship: 440
- name: Trekhalo
  scholarship: 450
- name: Giant
  scholarship: 460
- name: Bobcat
  scholarship: 470
- name: Snowbeast
  scholarship: 480
- name: Arzumos
  scholarship: 490
- name: Caracal
  scholarship: 500
- name: Firecat
  scholarship: 510
- name: Gryphon
  scholarship: 520
- name: Seordmaor
  scholarship: 530
- name: Bull
  scholarship: 540
- name: Mammoth
  scholarship: 550
- name: Hawk
  scholarship: 560
- name: Armadillo
  scholarship: 570
- name: Shark
  scholarship: 580
- name: La'heke
  scholarship: 590
- name: Angiswaerd
  scholarship: 600
- name: Toad
  scholarship: 610
- name: Elsralael
  scholarship: 620
- name: Celpeze
  scholarship: 630
- name: Spider
  scholarship: 640
- name: Silverfish
  scholarship: 650
- name: Crab
  scholarship: 660
- name: Westanuryn
  scholarship: 670
- name: Dolomar
  scholarship: 680
- name: Warklin
  scholarship: 690
- name: Wasp
  scholarship: 700
- name: Dryad
  scholarship: 710
- name: Fendryad
  scholarship: 720
- name: Sprite
  scholarship: 730
- name: Alfar
  scholarship: 740
- name: Frostweaver
  scholarship: 750
- name: Spriggan
  scholarship: 760
- name: Gremlin
  scholarship: 770
- name: Cyclops
  scholarship: 780
- name: Ati'ket
  scholarship: 790
- name: S'lai
  scholarship: 800
- name: Adan'f
  scholarship: 810
- name: Kra'hei
  scholarship: 820
- name: Faenrae
  scholarship: 830
- name: Bear
  scholarship: 840
- name: Barghest
  scholarship: 850
- name: Shalswar
  scholarship: 860
- name: Dyrachis
  scholarship: 870
- name: Poloh'izh
  scholarship: 880
- name: Korograth
  scholarship: 890
- name: Larva
  scholarship: 900
- name: Bizar
  scholarship: 910
- name: Pivuh
  scholarship: 920
- name: Vulture
  scholarship: 930
- name: Unyn
  scholarship: 940
- name: Moruryn
  scholarship: 950
- name: Moruryn
  scholarship: 950
- name: Kartais
  scholarship: 970
- name: Colepexy
  scholarship: 980
- name: Vykathi
  scholarship: 990
- name: Wyvern
  scholarship: 1000
- name: Elpalzi
  scholarship: 1050
- name: Xala'shar
  scholarship: 1050

```
