### ISSUE TITLE
Validate parser throwing erroneous error(s) regarding research_skills

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#855]
```
> ,validate
--- Lich: validate active.
[validate: Validating settings for 3 settings files]

[validate: Checking 28 different potential errors in file Ythryx-stealth.yaml]
[validate: ERROR:< Skill in research_skills could not be found in crossing_training. 'Utility'  >]
[validate: ERROR:< Skill in research_skills could not be found in crossing_training. 'Warding'  >]

[validate: Checking 28 different potential errors in file Ythryx-tm.yaml]
[validate: ERROR:< Skill in research_skills could not be found in crossing_training. 'Utility'  >]
[validate: ERROR:< Skill in research_skills could not be found in crossing_training. 'Warding'  >]

[validate: Checking 28 different potential errors in file Ythryx-fighting.yaml]
[validate: ERROR:< Skill in research_skills could not be found in crossing_training. 'Utility'  >]
[validate: ERROR:< Skill in research_skills could not be found in crossing_training. 'Warding'  >]
[validate: All done!]
```

In Ythryx-setup.yaml:

crossing_training:
- Scholarship
- Thievery
- First Aid
- Augmentation
- Arcana
- Holy Magic
- Theurgy
- Locksmithing
- Athletics
- Outdoorsmanship
- Attunement
- Mechanical Lore

cyclic_research_skills:
- Utility
- Warding

training_spells:
  Utility:
    abbrev: bless
    symbiosis: false
  Augmentation:
    abbrev: centering
    symbiosis: false
  Warding:
    abbrev: pfe
    symbiosis: false

research_training_spells:
  Warding:
    abbrev: GHS
    cyclic: true
  Utility:
    abbrev: REZZ
    cyclic: true
# REQUIRES GAUGE FLOW

use_research: true
research_skills:
- Augmentation
- Holy Magic
- Arcana
- Utility
- Warding

**Comment by rpherbig** [comment]
I don't see 'Utility' in your 'crossing_training' setting. Validate is trying to say that because of that, Utility won't get trained.

Is Utility being trained?

**Comment by cynesis** [comment]
Was editing in an interesting point; I'll leave it here.

Validate is throwing errors pertaining to the two skills listed under cyclic_research_skills. Those two are being trained while researching which is why they are not listed under crossing_training. Suspect some odd interaction with validate, crossing_training, cyclic_research_skills.

I will add those two under crossing_training for testing, but I do not wish them to be trained as normal (hence, cyclic_research_skills).

**Comment by drboldwin** [comment]
Research Skills are no longer used.

That being said there is likely a similar error being thrown for cyclic_cycle_skills  - though this is likely less noticeable as these are now designed to be listed under both training_skills and cyclic_cycle_skills.  Just with different spell choices.

```
training_spells:
  Warding:
    abbrev: SOS
    symbiosis: true
  Utility:
    abbrev: DR
    symbiosis: true
  Augmentation:
    abbrev: MAPP
    symbiosis: true

cyclic_training_spells:
  Warding:
    abbrev: GHS
    cyclic: true
  Utility:
    abbrev: REV
    cyclic: true
  Augmentation:
    abbrev: REV
    cyclic: true

crossing_training:
- Utility
- Warding
- Augmentation
cyclic_cycle_skills:
- Utility
- Warding
- Augmentation
```
