### ISSUE TITLE
Further Cambrinth Support

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#871]
so after working on allowing for some dedicated camb use I got to thinking.  The main flaw with this is the fact that we only support 1 camb item.  And so it really only allows for dedicated camb use to benefit using it as "spell" and not as "cyclic".  I was thinking perhaps reworking camb items and doing something in your YAML along the lines of:

```
cambinth:
- name: armband
  worn: true
  capacity: 32
  dedicated: spell
- name: camrinth orb
  worn: false
  capacity: 100
  dedicated: cyclic
```

addressing the recharging and relinking of your cyclic camb with some flags ( I think there is messaging when you flag breaks, and know that you could at least grab the line that says you harness mana to maintain the spell or whatnot).  Thoughts?
