### ISSUE TITLE
Separate cyclic spells from training spells

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#884]
Alright so I've been playing with this a bit this morning because I am always looking for the most efficient way to train my magics during crossing-training.

Currently we use training_spells: and I had previously added research_training_spells - what I was thinking is I scrap out research_training_spells and replace it with cyclic_training_spells.  And perhaps a toggle something akin to cyclic_cycle: true.

The way I am using cyclic cycle currently is with it's own timer (set to 300), it is checked BEFORE choosing a skill to train, and if it is off timer it will put up a new cyclic spell depending on lowest EXP.  Then crossing-training picks a skill as per normal, if that skill is aug/util/warding it casts from the training_spells list instead. 

- my quick code (I would likely change variable names and whatnot but is what I tossed together to test with)

**During initialize**
`    @cyclic_cycle_timer = Time.now - 300`
**During Event_Loop (call to refresh cyclics)**
```
    stop_play unless @researching
    refresh_cyclic

    echo "***Attempting to train #{skill}***" if UserVars.crossing_trainer_debug

    update_timer(skill)

    case skill
    when 'Appraisal'
      train_appraisal
    when 'Athletics'
      train_athletics
    when 'Arcana', 'Life Magic', 'Holy Magic', 'Lunar Magic', 'Elemental Magic', 'Arcane Magic'
      do_research skill
```
**It's method**
```
  def refresh_cyclic
    return unless @settings.cyclic_cycle
    if @settings.cyclic_training_spells && (Time.now - @cyclic_cycle_timer > 300)
      skill_pick = @settings.cyclic_cycle_skills
                                       .min_by { |s| DRSkill.getxp(s) }
      cast_spell(@settings.cyclic_training_spells[skill_pick], skill_pick)
      @cyclic_cycle_timer = Time.now
    end
  end
```
^^ Likely need to add a check against researching here also
`    return unless @settings.cyclic_cycle && !@researching`

But we can continue to refresh cyclics between projects by basically scrapping the entire cyclic research section by just throwing a call into def research:

```
  def research
    if @settings.cyclic_cycle
      refresh_cyclic
    end
```
I think we still need that since I feel like I remember the 2nd and 3rd call to research a project is independent of finding the next skill to train (which refresh_cyclic is called just beforehand) but I think for those moments in between projects @researching is false.  I'll have to test this.  But essentially should keep all current functionality and add further cyclic support.

------------------------------------------------------------------
**Overview**

What we would be allowing is separate listings of training spells and cyclic spells so that we can run cyclics while double dipping with casting spells in order to train magic faster overall.

There would be issues if people listed cyclics under both I imagine but since it would be an opt-in system, those who choose to use it would be doing so understanding of how it works.

**Comment by drboldwin** [comment]
This also sparked a little interest I had been floating around dealing with always losing cyclic spell during theurgy (the stairway in the temple)

The reading of the wall isn't suuuuper important - it's just some added devotion, so adding a check in there at the start of it to see if a cyclic is currently running and then either moving on (if one is) or studying the wall (if one isn't) would be good.  I threw something together and would likely bundle these changes.

```
  def study_wall
    return if DRStats.circle < 30
    get_data('spells')
      .spell_data
      .select { |_name, properties| properties['cyclic'] }
    return unless get_data('spells').spell_data.select { |name, _properties| DRSpells.active_spells.keys.include?(name) }.empty?
```

**Comment by drboldwin** [comment]
Except from my YAML as a sample setup:

```
# Non-combat settings
sell_loot_bundle: true
cyclic_cycle: true

training_spells:
  Warding:
    abbrev: SOS
    symbiosis: true
  Utility:
    abbrev: DR
    symbiosis: true
  Augmentation:
    abbrev: MAPP
    symbiosis: true

cyclic_training_spells:
  Warding:
    abbrev: GHS
    cyclic: true
  Utility:
    abbrev: REV
    cyclic: true
  Augmentation:
    abbrev: REV
    cyclic: true

exp_timers:
  Theurgy: 1800
  Attunement: 130
  Thievery: 600
crossing_training:
- Utility
- Warding
- Augmentation
- Sorcery
- Locksmithing
- Thievery
- First Aid
#- Arcana
#- Holy Magic
- Theurgy
- Athletics
- Outdoorsmanship
- Attunement
#- Mechanical Lore
#- Alchemy
cyclic_cycle_skills:
- Utility
- Warding
- Augmentation
```
