### ISSUE TITLE
Blacksmithing recipes to add to crafting_recipes

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#992]
```
- name: a sturdy metal drawknife
  noun: drawknife
  volume: 5
  type: blacksmithing
  work_order: true
  chapter: 3
  part:
  - short pole
- name: a sharpened metal drawknife
  noun: drawknife
  volume: 5
  type: blacksmithing
  work_order: true
  chapter: 3
  part:
  - short pole
- name: a rough metal wood shaper
  noun: shaper
  volume: 4
  chapter: 3
  type: blacksmithing
  work_order: true
- name: a metal jagged wood shaper
  noun: shaper
  volume: 4
  chapter: 3
  type: blacksmithing
  work_order: true
- name: some curved metal pliers
  noun: pliers
  volume: 5
  chapter: 3
  type: blacksmithing
  work_order: true
- name: some rough metal pliers
  noun: pliers
  volume: 5
  chapter: 3
  type: blacksmithing
  work_order: true
- name: some hooked metal pliers
  noun: pliers
  volume: 5
  chapter: 3
  type: blacksmithing
  work_order: true
- name: some ribbed sewing needles
  noun: needles
  volume: 3
  type: blacksmithing
  work_order: true
  chapter: 4
- name: some tapered knitting needles
  noun: needles
  volume: 3
  type: blacksmithing
  work_order: true
  chapter: 4
- name: some knobby sewing needles
  noun: needles
  volume: 3
  type: blacksmithing
  work_order: true
  chapter: 4
- name: some squat knitting needles
  noun: needles
  volume: 3
  type: blacksmithing
  work_order: true
  chapter: 4
- name: some thin sewing needles
  noun: needles
  volume: 3
  type: blacksmithing
  work_order: true
  chapter: 4
- name: a curved hide scraper
  noun: scraper
  volume: 3
  type: blacksmithing
  work_order: true
  chapter: 4
- name: a serrated hide scraper
  noun: scraper
  volume: 3
  type: blacksmithing
  work_order: true
  chapter: 4
- name: some serrated scissors
  noun: scissors
  volume: 4
  type: blacksmithing
  work_order: true
  chapter: 4
- name: a pointed metal awl
  noun: awl
  volume: 4
  type: blacksmithing
  work_order: true
  chapter: 4
- name: a compact metal awl
  noun: awl
  volume: 4
  type: blacksmithing
  work_order: true
  chapter: 4
- name: a slender metal awl
  noun: awl
  volume: 4
  type: blacksmithing
  work_order: true
  chapter: 4
```
